export const navItems = [
    { link: 'Dashboard', path: '/' },
    { link: 'Incidents', path: '/incidents' },
    { link: 'Locations', path: '/locations' },
    { link: 'Activities', path: '/activities' },
    { link: 'Documents', path: '/documents' },
    { link: 'Cypher AI', path: '/cypherai' },
];

export const DashboardInfo = [
    { path: 'img.png', alt: 'img ', title: 'Whitechapel Rd.', location: 'Tulare County,  Los Angles, CA 23415', tk: '$1,456,654.00' },
    { path: 'img1.png', alt: 'img 1', title: 'Whitechapel Rd.', location: 'Tulare County,  Los Angles, CA 23415', tk: '$1,456,654.00' },
    { path: 'img2.png', alt: 'img 2', title: 'Tulare County.', location: 'Tulare County,  Los Angles, CA 23415', tk: '$1,456,654.00' },
    { path: 'img3.png', alt: 'img 1', title: 'Tulare County', location: 'Tulare County,  Los Angles, CA 23415', tk: '$1,456,654.00' },
    { path: 'img4.png', alt: 'img 1', title: 'Tulare County', location: 'Tulare County,  Los Angles, CA 23415', tk: '$1,456,654.00' },
    { path: 'img5.png', alt: 'img 1', title: 'Tulare County', location: 'Tulare County,  Los Angles, CA 23415', tk: '$1,456,654.00' },
];

// Get Started Page card's Data here....
export const GetStartedPage = [
    {
        path: '/Frame.png', alt: 'Frame Image', title: 'What type of incident?',
        disc: 'Choose the category that best describes the incident.',
    },
    {
        path: '/Frame1.png', alt: 'Tell us about the incident?', title: 'Tell us about the incident?',
        disc: 'Let’s connect the dots and see where to start.',
    },
    {
        path: '/Frame2.png', alt: 'Where did the incident occur?', title: 'Where did the incident occur?',
        disc: 'Lorem ipsum dolar sit general sac mascho werho',
    }
];

// New Incident Card's Data
export const NewIncidentCards = [
    {path:'/icons/icon.png', name:'Avalanche'},
    {path:'/icons/icon1.png', name:'Biological'},
    {path:'/icons/icon2.png', name:'Blizzard'},
    {path:'/icons/icon3.png', name:'Cold/Freezing'},
    {path:'/icons/icon4.png', name:'Drought'},
    {path:'/icons/icon5.png', name:'Earthquake'},
    {path:'/icons/icon6.png', name:'Flooding'},
    {path:'/icons/icon7.png', name:'Heat Wave'},
    {path:'/icons/icon8.png', name:'Hail'},
    {path:'/icons/icon9.png', name:'Lightning'},
    {path:'/icons/icon10.png', name:'Man Made'},
    {path:'/icons/icon11.png', name:'Mudslide'},
    {path:'/icons/icon12.png', name:'Severe Storm'},
    {path:'/icons/icon13.png', name:'Strong Wind'},
    {path:'/icons/icon14.png', name:'Tornado'},
    {path:'/icons/icon15.png', name:'Tsunami'},
    {path:'/icons/icon16.png', name:'Volcanic Eruption'},
    {path:'/icons/icon17.png', name:'Wildfire'},
]


// Location Cards Data
export const locationData = [
    {
      id: 1,
      title: 'Whitechapel Rd.',
      address: 'Tulare County, Los Angeles, CA 23415',
      price: '$1,456,654.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 2,
      title: 'Sunset Blvd.',
      address: 'Orange County, Los Angeles, CA 92626',
      price: '$1,200,000.00',
      image: '/house1.png',
      tag: 'Building',
    },
    {
      id: 3,
      title: 'Elm Street',
      address: 'Santa Clara, San Jose, CA 95112',
      price: '$999,999.00',
      image: '/house2.png',
      tag: 'Building',
    },
    {
      id: 4,
      title: 'Beverly Hills',
      address: 'Beverly Hills, CA 90210',
      price: '$3,000,000.00',
      image: '/house3.png',
      tag: 'Building',
    },
    {
      id: 5,
      title: 'Hollywood Blvd.',
      address: 'Hollywood, Los Angeles, CA 90028',
      price: '$2,250,000.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 6,
      title: 'Maple Ave.',
      address: 'Fresno County, CA 93722',
      price: '$875,000.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 7,
      title: 'Ocean Drive',
      address: 'Santa Monica, CA 90401',
      price: '$1,650,000.00',
      image: '/house1.png',
      tag: 'Building',
    },
    {
      id: 8,
      title: 'Mission St.',
      address: 'San Francisco, CA 94110',
      price: '$1,990,000.00',
      image: '/house2.png',
      tag: 'Building',
    },
    {
      id: 9,
      title: 'Palm Tree Rd.',
      address: 'San Diego, CA 92103',
      price: '$1,375,000.00',
      image: '/house3.png',
      tag: 'Building',
    },
    {
      id: 10,
      title: 'Cedar St.',
      address: 'Long Beach, CA 90802',
      price: '$1,100,000.00',
      image: '/house.png',
      tag: 'Building',
    },
];
  
// Location Cards Data
export const activeCard = [
    {
      id: 1,
      title: 'Activity name',
      address: 'Location name . 16.12212, -122.1424',
      price: '$1,456,654.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 2,
      title: 'Activity name',
      address: 'Location name . 16.12212, -122.1424',
      price: '$1,200,000.00',
      image: '/house1.png',
      tag: 'Building',
    },
    {
      id: 3,
      title: 'Activity name',
      address: 'Location name . 16.12212, -122.1424',
      price: '$999,999.00',
      image: '/house2.png',
      tag: 'Building',
    },
    {
      id: 4,
      title: 'Beverly Hills',
      address: 'Location name . 16.12212, -122.1424',
      price: '$3,000,000.00',
      image: '/house3.png',
      tag: 'Building',
    },
    {
      id: 5,
      title: 'Hollywood Blvd.',
      address: 'Hollywood, Los Angeles, CA 90028',
      price: '$2,250,000.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 6,
      title: 'Maple Ave.',
      address: 'Fresno County, CA 93722',
      price: '$875,000.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 7,
      title: 'Ocean Drive',
      address: 'Santa Monica, CA 90401',
      price: '$1,650,000.00',
      image: '/house1.png',
      tag: 'Building',
    },
    {
      id: 8,
      title: 'Mission St.',
      address: 'San Francisco, CA 94110',
      price: '$1,990,000.00',
      image: '/house2.png',
      tag: 'Building',
    },
    {
      id: 9,
      title: 'Palm Tree Rd.',
      address: 'San Diego, CA 92103',
      price: '$1,375,000.00',
      image: '/house3.png',
      tag: 'Building',
    },
    {
      id: 10,
      title: 'Cedar St.',
      address: 'Long Beach, CA 90802',
      price: '$1,100,000.00',
      image: '/house.png',
      tag: 'Building',
    },
];
  
//Documents Cards Data
export const documentsCard = [
    {
      id: 1,
      title: 'Document Name',
      address: 'Location name . 16.12212, -122.1424',
      price: '$1,456,654.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 2,
      title: 'Document Name',
      address: 'Location name . 16.12212, -122.1424',
      price: '$1,200,000.00',
      image: '/house1.png',
      tag: 'Building',
    },
    {
      id: 3,
      title: 'Document Name',
      address: 'Location name . 16.12212, -122.1424',
      price: '$999,999.00',
      image: '/house2.png',
      tag: 'Building',
    },
    {
      id: 4,
      title: 'Document Name',
      address: 'Location name . 16.12212, -122.1424',
      price: '$3,000,000.00',
      image: '/house3.png',
      tag: 'Building',
    },
    {
      id: 5,
      title: 'Hollywood Blvd.',
      address: 'Hollywood, Los Angeles, CA 90028',
      price: '$2,250,000.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 6,
      title: 'Maple Ave.',
      address: 'Fresno County, CA 93722',
      price: '$875,000.00',
      image: '/house.png',
      tag: 'Building',
    },
    {
      id: 7,
      title: 'Ocean Drive',
      address: 'Santa Monica, CA 90401',
      price: '$1,650,000.00',
      image: '/house1.png',
      tag: 'Building',
    },
    {
      id: 8,
      title: 'Mission St.',
      address: 'San Francisco, CA 94110',
      price: '$1,990,000.00',
      image: '/house2.png',
      tag: 'Building',
    },
    {
      id: 9,
      title: 'Palm Tree Rd.',
      address: 'San Diego, CA 92103',
      price: '$1,375,000.00',
      image: '/house3.png',
      tag: 'Building',
    },
    {
      id: 10,
      title: 'Cedar St.',
      address: 'Long Beach, CA 90802',
      price: '$1,100,000.00',
      image: '/house.png',
      tag: 'Building',
    },
  ];